server:
  port: 9192

spring:
  application:
    name: kafka-consumer
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    # Needed because the consumer app internally produces messages to retry/DLT topics
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: test-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.dk.kafka.dtos
            value:
              default:
                type: com.dk.kafka.dtos.Customer

app:
  kafka:
    consumers:
      - topic: test-topic
        group-id: test-group
        alias: test
      - topic: customer-topic
        group-id: customer-group
        alias: customer

